#将静态内容部署到GUUUB页面的简单工作流
 姓名   : 名称 : 将静态内容部署到页面

 在…上   :
  #开始以默认分支为目标
  推动   :
    分枝   : [   "main"   ]

  #允许您从操作选项卡手动运行此工作流
  工作流程   :

#设置了使部署得以实现JUTUB页面的JUTUB_托肯权限
 准许   :
  目录   :      内容 : 改为
  页   :      页 : 书写
  令人印象深刻的   :      印 : 写

#只允许一个并发部署,在正在进行的运行和最新的队列之间跳过排队的运行。
#但是,不要取消正在进行的运行,因为我们希望允许这些生产部署完成。
 并发的   :
  团体   : "pages"
  正在取消的   : 假的

乔布斯 :
  #单一部署任务因为我们刚刚部署
  部署  :
    环境   :
      姓名 :github-pages
      乌拉圭网址 :$ {    { steps.deployment.outputs.page_url }    }
    逃跑 :ubuntu-latest
    台阶    :
      - 姓名 :Checkout
        使用 :actions/checkout@v4
      - 姓名:设置页
        使用 :actions/configure-pages@v5
      - 姓名:上传艺术品
        使用 :actions/upload-pages-artifact@v3
        与…有关    :
          #上载整个储存库
          通道    : '.'
      - 姓名:部署到千分通页
        身份证 :deployment
        用途:行动/部署页@V4
